micronaut:
  application:
    name: cloudTest
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
              jws-algorithm: HS256
netty:
  default:
    allocator:
      max-order: 3

mongodb:
  uri: mongodb+srv://mdbatista:ZUr8wc9BMYdH8N9p@dedicated.kavqe.mongodb.net/four-paws-kot
